name: daily_masjid
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^2.1.0 
  dio: ^5.0.3
  get_storage: ^2.0.3
  package_info_plus: ^3.0.3
  url_launcher: ^6.1.10
  flutter_share: ^2.0.0
  flutter_screenutil: ^5.7.0
  carousel_slider: ^4.0.0

  flutter_staggered_grid_view: ^0.6.2

  flutter_map: ^4.0.0
  flutter_geocoder: ^0.2.2-nullsafety
  latlong2: ^0.8.1
  maps_launcher: ^2.2.0

  fluttertoast: ^8.2.1

  flutter: 
    sdk: flutter
  
 

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

  change_app_package_name: ^1.1.0
  # flutter_launcher_name: "^0.0.1"
  flutter_launcher_icons: ^0.13.1


flutter_launcher_name:
  name: "Cek Catat Tagihan WIFI"
  
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 16

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

